// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaGPPu6HswSKhcV5FqL443C5vOWrj8me4',
    appId: '1:507012537441:web:99fb1615571824fceb5e20',
    messagingSenderId: '507012537441',
    projectId: 'chat-app-9dbcd',
    authDomain: 'chat-app-9dbcd.firebaseapp.com',
    storageBucket: 'chat-app-9dbcd.appspot.com',
    measurementId: 'G-G6P4N776RG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq244_FSavhUVXy2J7l9vxJ8YW4AeJJIQ',
    appId: '1:507012537441:android:185a23ff034b1955eb5e20',
    messagingSenderId: '507012537441',
    projectId: 'chat-app-9dbcd',
    storageBucket: 'chat-app-9dbcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPWONosmLtR9NVKYSWEySUiWJ7OUZuhOg',
    appId: '1:507012537441:ios:a0b575cad4bc77feeb5e20',
    messagingSenderId: '507012537441',
    projectId: 'chat-app-9dbcd',
    storageBucket: 'chat-app-9dbcd.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
